packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bcrypt: true
  bufferutil: true
  canvas: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  sqlite3: true
catalog:
    typescript: "^7.0.2"
catalogMode: manual
